from __future__ import annotations

from datetime import date

import pandas as pd

SALES_DATA = pd.DataFrame(
    {
        "product_category": [
            "Electronics",
            "Electronics",
            "Electronics",
            "Electronics",
            "Clothing",
            "Clothing",
            "Clothing",
            "Clothing",
            "Food",
            "Food",
            "Food",
            "Food",
            "Electronics",
            "Clothing",
            "Food",
            "Electronics",
            "Clothing",
            "Food",
        ],
        "region": [
            "North",
            "South",
            "East",
            "West",
            "North",
            "South",
            "East",
            "West",
            "North",
            "South",
            "East",
            "West",
            "North",
            "South",
            "East",
            "West",
            "East",
            "North",
        ],
        "sale_date": pd.to_datetime(
            [
                date(2024, 1, 15),
                date(2024, 1, 20),
                date(2024, 2, 10),
                date(2024, 2, 28),
                date(2024, 1, 5),
                date(2024, 1, 18),
                date(2024, 2, 14),
                date(2024, 3, 1),
                date(2024, 1, 10),
                date(2024, 2, 5),
                date(2024, 2, 20),
                date(2024, 3, 15),
                date(2024, 3, 10),
                date(2024, 3, 20),
                date(2024, 3, 25),
                date(2024, 4, 1),
                date(2024, 4, 10),
                date(2024, 4, 15),
            ]
        ),
        "revenue": [
            1200.50,
            850.00,
            2100.75,
            675.25,
            450.00,
            380.50,
            290.00,
            520.75,
            150.25,
            200.00,
            175.50,
            310.00,
            1800.00,
            620.00,
            280.50,
            950.25,
            410.00,
            195.75,
        ],
        "units_sold": [
            10,
            7,
            15,
            5,
            12,
            8,
            6,
            14,
            25,
            30,
            20,
            40,
            12,
            15,
            35,
            8,
            10,
            28,
        ],
        "price": [
            120.05,
            121.43,
            140.05,
            135.05,
            37.50,
            47.56,
            48.33,
            37.20,
            6.01,
            6.67,
            8.78,
            7.75,
            150.00,
            41.33,
            8.01,
            118.78,
            41.00,
            6.99,
        ],
    }
)

# Metric definitions: metric_id -> (source_column, aggregation_function)
METRIC_DEFINITIONS: dict[str, tuple[str, str]] = {
    "sales.total_revenue": ("revenue", "sum"),
    "sales.total_units_sold": ("units_sold", "sum"),
    "sales.average_price": ("price", "mean"),
}

# Dimension definitions: dimension_id -> source_column
DIMENSION_COLUMNS: dict[str, str] = {
    "sales.product_category": "product_category",
    "sales.region": "region",
    "sales.sale_date": "sale_date",
}
