from __future__ import annotations

from datetime import date

import pyarrow as pa

SALES_DATA = pa.table(
    {
        "product_category": [
            "Electronics",
            "Electronics",
            "Electronics",
            "Electronics",
            "Clothing",
            "Clothing",
            "Clothing",
            "Clothing",
            "Food",
            "Food",
            "Food",
            "Food",
            "Electronics",
            "Clothing",
            "Food",
            "Electronics",
            "Clothing",
            "Food",
        ],
        "region": [
            "North",
            "South",
            "East",
            "West",
            "North",
            "South",
            "East",
            "West",
            "North",
            "South",
            "East",
            "West",
            "North",
            "South",
            "East",
            "West",
            "East",
            "North",
        ],
        "customer_segment": [
            "Enterprise",
            "SMB",
            "Consumer",
            "Enterprise",
            "Consumer",
            "SMB",
            "Consumer",
            "Enterprise",
            "Consumer",
            "Consumer",
            "SMB",
            "Enterprise",
            "Enterprise",
            "SMB",
            "Consumer",
            "Enterprise",
            "SMB",
            "Consumer",
        ],
        "return_reason": [
            "No Return",
            "Damaged",
            "No Return",
            "No Return",
            "No Return",
            "Wrong Size",
            "No Return",
            "No Return",
            "Expired",
            "No Return",
            "Expired",
            "No Return",
            "No Return",
            "Wrong Size",
            "No Return",
            "No Return",
            "Wrong Size",
            "No Return",
        ],
        "sale_date": [
            date(2024, 1, 15),
            date(2024, 1, 20),
            date(2024, 2, 10),
            date(2024, 2, 28),
            date(2024, 1, 5),
            date(2024, 1, 18),
            date(2024, 2, 14),
            date(2024, 3, 1),
            date(2024, 1, 10),
            date(2024, 2, 5),
            date(2024, 2, 20),
            date(2024, 3, 15),
            date(2024, 3, 10),
            date(2024, 3, 20),
            date(2024, 3, 25),
            date(2024, 4, 1),
            date(2024, 4, 10),
            date(2024, 4, 15),
        ],
        "revenue": [
            1200.50,
            850.00,
            2100.75,
            675.25,
            450.00,
            380.50,
            290.00,
            520.75,
            150.25,
            200.00,
            175.50,
            310.00,
            1800.00,
            620.00,
            280.50,
            950.25,
            410.00,
            195.75,
        ],
        "units_sold": [
            10,
            7,
            15,
            5,
            12,
            8,
            6,
            14,
            25,
            30,
            20,
            40,
            12,
            15,
            35,
            8,
            10,
            28,
        ],
        "price": [
            120.05,
            121.43,
            140.05,
            135.05,
            37.50,
            47.56,
            48.33,
            37.20,
            6.01,
            6.67,
            8.78,
            7.75,
            150.00,
            41.33,
            8.01,
            118.78,
            41.00,
            6.99,
        ],
        "campaign_channel": [
            "Search",
            "Social",
            "Search",
            "Email",
            "Affiliate",
            "Social",
            "Affiliate",
            "Email",
            "Search",
            "Social",
            "Search",
            "Email",
            "Search",
            "Social",
            "Affiliate",
            "Email",
            "Affiliate",
            "Social",
        ],
        "device_type": [
            "Desktop",
            "Mobile",
            "Desktop",
            "Tablet",
            "Mobile",
            "Mobile",
            "Desktop",
            "Tablet",
            "Desktop",
            "Mobile",
            "Desktop",
            "Tablet",
            "Desktop",
            "Mobile",
            "Desktop",
            "Tablet",
            "Mobile",
            "Mobile",
        ],
        "ad_spend": [
            420.0,
            390.0,
            510.0,
            210.0,
            140.0,
            160.0,
            110.0,
            155.0,
            80.0,
            92.0,
            89.0,
            120.0,
            380.0,
            170.0,
            105.0,
            260.0,
            130.0,
            97.0,
        ],
        "impressions": [
            14000,
            12000,
            16000,
            7000,
            5000,
            6000,
            4200,
            5600,
            3800,
            4000,
            3900,
            5100,
            13200,
            6200,
            4300,
            8700,
            5200,
            4050,
        ],
        "clicks": [
            480,
            455,
            610,
            240,
            160,
            205,
            130,
            175,
            120,
            132,
            126,
            165,
            445,
            210,
            140,
            288,
            172,
            136,
        ],
        "returned_units": [
            0,
            1,
            0,
            0,
            0,
            2,
            0,
            0,
            3,
            0,
            2,
            0,
            0,
            1,
            0,
            0,
            1,
            0,
        ],
    }
)

# Metric definitions: metric_id -> (source_column, aggregation_function)
# Aggregation function names follow PyArrow's group_by convention.
METRIC_DEFINITIONS: dict[str, tuple[str, str]] = {
    "sales.total_revenue": ("revenue", "sum"),
    "sales.total_units_sold": ("units_sold", "sum"),
    "sales.average_price": ("price", "mean"),
    "sales.returned_units": ("returned_units", "sum"),
    "marketing.total_ad_spend": ("ad_spend", "sum"),
    "marketing.total_impressions": ("impressions", "sum"),
    "marketing.total_clicks": ("clicks", "sum"),
}

METRIC_METADATA: dict[str, dict[str, str | pa.DataType]] = {
    "sales.total_revenue": {
        "name": "total_revenue",
        "type": pa.float64(),
        "definition": "SUM(revenue)",
        "description": "Total sales revenue.",
    },
    "sales.total_units_sold": {
        "name": "total_units_sold",
        "type": pa.int64(),
        "definition": "SUM(units_sold)",
        "description": "Total units sold.",
    },
    "sales.average_price": {
        "name": "average_price",
        "type": pa.float64(),
        "definition": "AVG(price)",
        "description": "Average selling price.",
    },
    "sales.returned_units": {
        "name": "returned_units",
        "type": pa.int64(),
        "definition": "SUM(returned_units)",
        "description": "Total returned units.",
    },
    "marketing.total_ad_spend": {
        "name": "total_ad_spend",
        "type": pa.float64(),
        "definition": "SUM(ad_spend)",
        "description": "Total marketing spend.",
    },
    "marketing.total_impressions": {
        "name": "total_impressions",
        "type": pa.int64(),
        "definition": "SUM(impressions)",
        "description": "Total ad impressions.",
    },
    "marketing.total_clicks": {
        "name": "total_clicks",
        "type": pa.int64(),
        "definition": "SUM(clicks)",
        "description": "Total ad clicks.",
    },
}

# Dimension definitions: dimension_id -> source_column
DIMENSION_COLUMNS: dict[str, str] = {
    "sales.product_category": "product_category",
    "sales.region": "region",
    "sales.sale_date": "sale_date",
    "sales.customer_segment": "customer_segment",
    "sales.return_reason": "return_reason",
    "marketing.campaign_channel": "campaign_channel",
    "marketing.device_type": "device_type",
}

DIMENSION_TYPES: dict[str, pa.DataType] = {
    "sales.product_category": pa.utf8(),
    "sales.region": pa.utf8(),
    "sales.sale_date": pa.date32(),
    "sales.customer_segment": pa.utf8(),
    "sales.return_reason": pa.utf8(),
    "marketing.campaign_channel": pa.utf8(),
    "marketing.device_type": pa.utf8(),
}

METRIC_DIMENSION_COMPATIBILITY: dict[str, set[str]] = {
    "sales.total_revenue": {
        "sales.product_category",
        "sales.region",
        "sales.sale_date",
        "sales.customer_segment",
    },
    "sales.total_units_sold": {
        "sales.product_category",
        "sales.region",
        "sales.sale_date",
        "sales.customer_segment",
    },
    "sales.average_price": {
        "sales.product_category",
        "sales.region",
        "sales.sale_date",
        "sales.customer_segment",
    },
    "sales.returned_units": {
        "sales.product_category",
        "sales.region",
        "sales.sale_date",
        "sales.customer_segment",
        "sales.return_reason",
    },
    "marketing.total_ad_spend": {
        "marketing.campaign_channel",
        "marketing.device_type",
        "sales.region",
        "sales.sale_date",
    },
    "marketing.total_impressions": {
        "marketing.campaign_channel",
        "marketing.device_type",
        "sales.region",
        "sales.sale_date",
    },
    "marketing.total_clicks": {
        "marketing.campaign_channel",
        "marketing.device_type",
        "sales.region",
        "sales.sale_date",
    },
}

METRIC_COMPATIBILITY: dict[str, set[str]] = {
    "sales.total_revenue": {
        "sales.total_revenue",
        "sales.total_units_sold",
        "sales.average_price",
        "sales.returned_units",
        "marketing.total_ad_spend",
    },
    "sales.total_units_sold": {
        "sales.total_revenue",
        "sales.total_units_sold",
        "sales.average_price",
        "sales.returned_units",
    },
    "sales.average_price": {
        "sales.total_revenue",
        "sales.total_units_sold",
        "sales.average_price",
        "sales.returned_units",
    },
    "sales.returned_units": {
        "sales.total_revenue",
        "sales.total_units_sold",
        "sales.average_price",
        "sales.returned_units",
    },
    "marketing.total_ad_spend": {
        "marketing.total_ad_spend",
        "marketing.total_impressions",
        "marketing.total_clicks",
        "sales.total_revenue",
    },
    "marketing.total_impressions": {
        "marketing.total_ad_spend",
        "marketing.total_impressions",
        "marketing.total_clicks",
    },
    "marketing.total_clicks": {
        "marketing.total_ad_spend",
        "marketing.total_impressions",
        "marketing.total_clicks",
    },
}

SEMANTIC_VIEW_DEFINITIONS: dict[str, dict[str, set[str]]] = {
    "sales": {
        "metrics": {
            "sales.total_revenue",
            "sales.total_units_sold",
            "sales.average_price",
            "sales.returned_units",
            "marketing.total_ad_spend",
        },
        "dimensions": {
            "sales.product_category",
            "sales.region",
            "sales.sale_date",
            "sales.customer_segment",
            "sales.return_reason",
            "marketing.campaign_channel",
        },
    },
    "marketing": {
        "metrics": {
            "marketing.total_ad_spend",
            "marketing.total_impressions",
            "marketing.total_clicks",
            "sales.total_revenue",
        },
        "dimensions": {
            "marketing.campaign_channel",
            "marketing.device_type",
            "sales.region",
            "sales.sale_date",
            "sales.product_category",
        },
    },
}
